---
driver:
  name: vagrant
  require_chef_omnibus: '11.10.4'

platforms:
- name: ubuntu-12.04
  driver_config:
    image_id: '80fbcb55-b206-41f9-9bc2-2dd7aac6c061'
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
- name: centos-6.4
  driver_config:
    image_id: 'f70ed7c7-b42e-4d77-83d8-40fa29825b85'
    box: opscode-centos-6.4
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.4_chef-provisionerless.box
- name: debian-7.2.0
  driver_config:
    image_id: '857d7d36-34f3-409f-8435-693e8797be8b'
    box: opscode-debian-7.2.0
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.2.0_chef-provisionerless.box

suites:
- name: default
  run_list:
  - recipe[rackspace_iptables_test]
  attributes: {}
