---
################################################################################
# Any local customizations should be placed inside the .kitchen.local.yml, which
# will not be checked in or overwritten. You may also use ~/.kitchen/config.yml
# or environment variables like VAGRANT_DEFAULT_PROVIDER. Anything in those will
# take precedence over anything set in `.kitchen.yml`.
################################################################################
driver:
  name: vagrant # provide a default test-kitchen driver, vagrant

driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  client_rb:
    environment: _default
  attributes:
    openssh:
      server:
        password_authentication: 'yes'
        permit_root_login: 'yes'
    cloud:
      public_ipv4: '127.0.0.1'
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    platformstack:
      cloud_backup:
        enabled: false
      cloud_monitoring:
        enabled: false
      omnibus_updater:
        enabled: false
      iptables:
        allow_ssh_from_world: true
    rackspace:
      cloud_credentials:
        username: 'racker'
        api_key: 'sekrit'

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: centos-6.5
    run_list:
    - recipe[yum]

suites:
  - name: default
    run_list: recipe[rackspace_iptables_test]
    attributes:
      foo: 'bar'
